Popup feature
gak92/Ghazanfar_Portfolio pull request #12
Opened 2022-06-15 08:06 UTC by gak92

In this pull request I implemented:

- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- When the user clicks (or taps) the close (X) button, the popup disappears.
- I implemented it for the Mobile version and for the Desktop version.

2022-06-15 20:36 UTC, youmari requested changes
Hi @gak92 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great title and short summary 
✔️ Github flow 
✔️ Good commit messages
✔️ No linter error

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 20:36 UTC, youmari commented on index.html
> +              </button>
- [ ] please try to remove this project cause you should generate cards dynamically please try to fix that

2022-06-15 20:36 UTC, youmari commented on index.html
> +      <div id="card1" class="card-works popup-card">
- [ ] please try to make the pop-up responsive in the mobile version and in the desktop version and try to remove the scroll bar and all the content of popUp should be displayed 
![image](https://user-images.githubusercontent.com/61790587/173922119-587d1bf0-3be6-4ecd-9c23-a49d20c30feb.png)
![image](https://user-images.githubusercontent.com/61790587/173922132-f1b7070c-a058-4bdf-985a-d005988753c8.png)

2022-06-16 08:25 UTC, ishimwezachee requested changes
Hi @gak92 and @bahoz-ali , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Ishimwe Zachee  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
(Not automatically expanded because 3 MB is too large. You can [expand it anyway](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) or [open it in a new window](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966).)

2022-06-16 08:25 UTC, ishimwezachee commented on index.html
> +    <script defer src="./script/index.js" type="module"></script>
- [ ] You have done some changes to implement the changes from the previous reviewer, but you still miss something. Your pop is still not responsive to both mobile and desktop devices. When I click to see project button,  I can only see the image, but I can't see the description.
![image](https://user-images.githubusercontent.com/43877689/174025802-c1cf1a71-d71a-48c5-9893-f908bb25f6e8.png)

- [ ]  Your description is outside of the card, please try to fix it as well by adjusting your image.
![image](https://user-images.githubusercontent.com/43877689/174026325-71acf079-c31f-4e2b-9885-b710a5f9fab6.png)


Maybe reducing the height of the image will help so that you popup will be well responsive.

2022-06-16 08:55 UTC, gak92 commented on index.html
> +    <script defer src="./script/index.js" type="module"></script>
@[ishimwezachee](https://github.com/ishimwezachee)
I fixed the responsiveness.

2022-06-16 09:43 UTC, gak92 commented on index.html
> +              </button>
@[chaw-bot](https://github.com/chaw-bot)
I don't understand which one to remove. I created the popup card dynamically using javascript.
Could you please explain it?
Thanks

2022-06-16 11:58 UTC, gak92 commented on index.html
> +              </button>
@[chaw-bot](https://github.com/chaw-bot)
I made the required changes:
- Removed cards from the index.html
- Cards data is loaded into HTML dynamically from the index.js

2022-06-16 12:04 UTC, ShadyShawkat approved these changes
## Hi @gak92, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-16 12:08 UTC, merged