Add form Section to the Portfolio
gak92/Ghazanfar_Portfolio pull request #3
Opened 2022-05-31 13:29 UTC by gak92

In this part of the project I added:
Contact Form Section in index.html
Also, update the style.css for this section

2022-05-31 19:35 UTC, Ginohmk requested changes
Hi @gak92 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Linter all green :+1: 
- Clean code :+1: 
- Professional PR nameing :100: 
- Good commit message :100: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 19:35 UTC, koachcode commented on index.html
> +              </li>
- Please there is an extra white line by the right of your webpage, that should not be there, please try as a must to follow the Figma design.

##### Figma design
![Screenshot from 2022-05-31 20-29-39](https://user-images.githubusercontent.com/58771507/171269618-9f2bde2d-f539-42aa-853a-f1520da7abe0.png)

##### Your design 
![Screenshot from 2022-05-31 20-25-21](https://user-images.githubusercontent.com/58771507/171269396-44344caa-472e-490a-9716-81c82878e894.png)

Please feel free to reach out to me if you need further, explanation of this feedback on slack, `@ kanu mike chibundu`

2022-05-31 19:35 UTC, Ginohmk commented on index.html
> +          >
- Please check the action URL, I think it is missing the form_id you got from `freespree`, it makes your form not work or post the intended message, Please try to fix it and test it works on your end.

2022-06-01 11:36 UTC, topeogunleye approved these changes
### Hi @gak92, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 12:15 UTC, merged